/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsTn2026VoterParticipationRouteImport } from './routes/blogs.tn-2026-voter-participation'
import { Route as BlogsRonaldoVsMessiGoatRouteImport } from './routes/blogs.ronaldo-vs-messi-goat'
import { Route as BlogsDelimitation816SeatsRouteImport } from './routes/blogs.delimitation-816-seats'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsTn2026VoterParticipationRoute =
  BlogsTn2026VoterParticipationRouteImport.update({
    id: '/blogs/tn-2026-voter-participation',
    path: '/blogs/tn-2026-voter-participation',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsRonaldoVsMessiGoatRoute = BlogsRonaldoVsMessiGoatRouteImport.update({
  id: '/blogs/ronaldo-vs-messi-goat',
  path: '/blogs/ronaldo-vs-messi-goat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsDelimitation816SeatsRoute =
  BlogsDelimitation816SeatsRouteImport.update({
    id: '/blogs/delimitation-816-seats',
    path: '/blogs/delimitation-816-seats',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/delimitation-816-seats': typeof BlogsDelimitation816SeatsRoute
  '/blogs/ronaldo-vs-messi-goat': typeof BlogsRonaldoVsMessiGoatRoute
  '/blogs/tn-2026-voter-participation': typeof BlogsTn2026VoterParticipationRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/delimitation-816-seats': typeof BlogsDelimitation816SeatsRoute
  '/blogs/ronaldo-vs-messi-goat': typeof BlogsRonaldoVsMessiGoatRoute
  '/blogs/tn-2026-voter-participation': typeof BlogsTn2026VoterParticipationRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/delimitation-816-seats': typeof BlogsDelimitation816SeatsRoute
  '/blogs/ronaldo-vs-messi-goat': typeof BlogsRonaldoVsMessiGoatRoute
  '/blogs/tn-2026-voter-participation': typeof BlogsTn2026VoterParticipationRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/blogs/$slug'
    | '/blogs/delimitation-816-seats'
    | '/blogs/ronaldo-vs-messi-goat'
    | '/blogs/tn-2026-voter-participation'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/blogs/$slug'
    | '/blogs/delimitation-816-seats'
    | '/blogs/ronaldo-vs-messi-goat'
    | '/blogs/tn-2026-voter-participation'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/blogs/$slug'
    | '/blogs/delimitation-816-seats'
    | '/blogs/ronaldo-vs-messi-goat'
    | '/blogs/tn-2026-voter-participation'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsDelimitation816SeatsRoute: typeof BlogsDelimitation816SeatsRoute
  BlogsRonaldoVsMessiGoatRoute: typeof BlogsRonaldoVsMessiGoatRoute
  BlogsTn2026VoterParticipationRoute: typeof BlogsTn2026VoterParticipationRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/tn-2026-voter-participation': {
      id: '/blogs/tn-2026-voter-participation'
      path: '/blogs/tn-2026-voter-participation'
      fullPath: '/blogs/tn-2026-voter-participation'
      preLoaderRoute: typeof BlogsTn2026VoterParticipationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/ronaldo-vs-messi-goat': {
      id: '/blogs/ronaldo-vs-messi-goat'
      path: '/blogs/ronaldo-vs-messi-goat'
      fullPath: '/blogs/ronaldo-vs-messi-goat'
      preLoaderRoute: typeof BlogsRonaldoVsMessiGoatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/delimitation-816-seats': {
      id: '/blogs/delimitation-816-seats'
      path: '/blogs/delimitation-816-seats'
      fullPath: '/blogs/delimitation-816-seats'
      preLoaderRoute: typeof BlogsDelimitation816SeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsDelimitation816SeatsRoute: BlogsDelimitation816SeatsRoute,
  BlogsRonaldoVsMessiGoatRoute: BlogsRonaldoVsMessiGoatRoute,
  BlogsTn2026VoterParticipationRoute: BlogsTn2026VoterParticipationRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
